filebeat.inputs:
- type: filestream
  paths: ["/var/log/syslog-ng-for-filebeat/filebeat-input.json"]
  parsers:
    - ndjson:
        add_error_key: true
  json.keys_under_root: true
  json.add_error_key: true
  json.overwrite_keys: true
  ignore_older: 0
  scan_frequency: 5s
  clean_removed: true
  close.on_state_change.inactive: 5m
  close.on_state_change.renamed: true

output.logstash:
  hosts: ["logstash:5044"]
  ssl.enabled: false
  timeout: 30s
  bulk_max_size: 512
  worker: 2
  loadbalance: true

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644

processors:
  - add_fields:
      target: host
      fields:
        name: "${HOSTNAME}"
  - add_host_metadata: ~
